### ISSUE TITLE
Baud rate

### ISSUE THREAD

**Issue by incmve** [saberone/pimatic-smartmeter#1]
Hi nice work on the plugin.
My meter uses a different baud rate, could you make the baud rate a config option aswel?

```
{
  "plugin": "smartmeter",
  "serialport": "/dev/ttyUSB0",
  "baudrate": 115200
}
```

EDIT my meter also uses 8N1 :(
maybe other options aswel so more people will be able to use it
baudRate: 115200,
        dataBits: 7,
        parity: 'even',
        stopBits: 1,
        flowControl: true,

**Comment by saberone** [comment]
Added the config options like you suggested. Check https://github.com/saberone/pimatic-smartmeter/blob/master/README.md for the settings. Tested it on my Raspberry and it should work. Let me know if works for you.

**Comment by incmve** [comment]
Fast work :+1: Going to test today

**Comment by incmve** [comment]
I'm not getting any data maybe my readouts are a bit different and the RegExResult don't match?

```
/KFM5KAIFA-METER

1-3:0.2.8(42)
0-0:1.0.0(150614130001S)
0-0:96.1.1(4530303235303030303230303932343134)
1-0:1.8.1(000377.539*kWh)
1-0:1.8.2(000294.336*kWh)
1-0:2.8.1(000000.000*kWh)
1-0:2.8.2(000000.000*kWh)
0-0:96.14.0(0001)
1-0:1.7.0(00.432*kW)
1-0:2.7.0(00.000*kW)
0-0:96.7.21(00009)
0-0:96.7.9(00007)
1-0:99.97.0(1)(0-0:96.7.19)(000101000001W)(2147483647*s)
1-0:32.32.0(00000)
1-0:32.36.0(00000)
0-0:96.13.1()
0-0:96.13.0()
1-0:31.7.0(002*A)
1-0:21.7.0(00.432*kW)
1-0:22.7.0(00.000*kW)
!5B8B
```

**Comment by saberone** [comment]
I have updated the regex so that it also matches the total usage with output from your smartmeter. So now this version logs the "raw" data and parsed data in pimatic-daemon.log. This helps to see what might be wrong when reading the data.

Example of what's in my pimatic-daemon.log is spitting out :

```
Raw data received:
/KMP5 KA6U001552741511

0-0:96.1.1(204B413655303031353532373431353131)
1-0:1.8.1(06569.000*kWh)
1-0:1.8.2(05208.000*kWh)
1-0:2.8.1(00000.000*kWh)
1-0:2.8.2(00000.000*kWh)
0-0:96.14.0(0001)
1-0:1.7.0(0000.22*kW)
1-0:2.7.0(0000.00*kW)
0-0:17.0.0(999*A)
0-0:96.3.10(1)
0-0:96.13.1()
0-0:96.13.0()
```

```
Parsed data:
{ tariffOneTotalUsage: 6569,
  tariffTwoTotalUsage: 5208,
  currentTariff: 1,
  currentUsage: 210 }
```

**Comment by incmve** [comment]
I have updated but still nothing, I'm not seeing anything in the log ether.
I am using the log reader atm with the following regex

```
{2}
match   :   1-0:1\\.8\\.1\\x28([0-9]+\\.[0-9]+).kWh\\x29
tarief1 :   $1
    1       {2}
match   :   1-0:1\\.8\\.2\\x28([0-9]+\\.[0-9]+).kWh\\x29
tarief2 :   $1
```

**Comment by saberone** [comment]
The request seems to be implemented and working. So closing this issue.

**Comment by incmve** [comment]
Working good, thanks :+1:
